### ISSUE TITLE
python library for raspberry pi?

### ISSUE THREAD

**Issue by ckoven** [sparkfun/SparkFun_GPS_Breakout_XA1110_Qwiic#1]
Hi All -- do you have any plans to include a python library for using the XA1110 GPS via the i2c interface on a raspberry pi?  Thanks for any info or help you can offer!

**Comment by nseidle** [comment]
It is planned but it will be a few more weeks. Feel like helping? ;)

**Comment by ckoven** [comment]
great! I'd love to but don't have the right skills. thanks!

**Comment by bboyho** [comment]
@ckoven , I'm not sure if you are aware but the library has been released for a while => [https://github.com/sparkfun/Qwiic_Titan_Gps_Py](https://github.com/sparkfun/Qwiic_Titan_Gps_Py).

Closing this out. =)
